# Generated by Django 4.2.4.dev20230711094537 on 2023-07-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('girls', models.JSONField()),
                ('ssrs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('level', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=3)),
                ('photo_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('effect1', models.CharField(max_length=30)),
                ('effect2', models.CharField(max_length=30)),
                ('effect3', models.CharField(max_length=30)),
                ('effect4', models.CharField(max_length=30)),
                ('effect5', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=2)),
                ('pp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ssr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=5)),
                ('girls', models.JSONField()),
                ('mod', models.BooleanField(default=False)),
                ('Malfunction', models.BooleanField(default=False)),
                ('skill_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill1', to='SSR.skill')),
                ('skill_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill2', to='SSR.skill')),
                ('skill_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill3', to='SSR.skill')),
            ],
        ),
    ]
