# Generated by Django 4.2.4.dev20230718095858 on 2023-07-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('girls_detail', models.JSONField(blank=True)),
                ('ssrs_detail', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('effect1', models.CharField(max_length=30)),
                ('effect2', models.CharField(blank=True, max_length=30)),
                ('effect3', models.CharField(blank=True, max_length=30)),
                ('effect4', models.CharField(blank=True, max_length=30)),
                ('effect5', models.CharField(blank=True, max_length=30)),
                ('effect6', models.CharField(blank=True, max_length=30)),
                ('effect7', models.CharField(blank=True, max_length=30)),
                ('skill_type', models.CharField(choices=[('A', 'A'), ('P', 'P'), ('F', 'F')], max_length=1)),
                ('skill_category', models.CharField(choices=[('POW', 'POW'), ('TEC', 'TEC'), ('STM', 'STM'), ('APL', 'APL'), ('SP', 'SP')], max_length=3)),
                ('pp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ssr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=5)),
                ('mod', models.BooleanField(default=False)),
                ('Malfunction', models.BooleanField(default=False)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girl', to='SSR.girl')),
                ('skill_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill1', to='SSR.skill')),
                ('skill_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill2', to='SSR.skill')),
                ('skill_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill3', to='SSR.skill')),
            ],
        ),
    ]
