# Generated by Django 4.2.4.dev20230718095858 on 2023-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girl',
            name='type',
            field=models.CharField(choices=[('POW', 'POW'), ('TEC', 'TEC'), ('STM+POW', 'STM+POW'), ('STM+TEC', 'STM+TEC')], max_length=7),
        ),
    ]
