# Generated by Django 4.2.4.dev20230711094537 on 2023-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ssrs',
        ),
        migrations.AddField(
            model_name='girl',
            name='ssrs_detail',
            field=models.JSONField(default=['']),
        ),
    ]
