# Generated by Django 4.2.4.dev20230718095858 on 2023-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSR', '0002_girl_birthday_alter_girl_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssr',
            name='type',
            field=models.CharField(choices=[('POW', 'POW'), ('TEC', 'TEC'), ('STM', 'STM'), ('APL', 'APL')], max_length=3),
        ),
    ]
