# Generated by Django 4.2.4.dev20230718095858 on 2023-08-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSR', '0003_alter_ssr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=25),
        ),
    ]
