# Generated by Django 4.2.4.dev20230711094537 on 2023-07-18 09:10

import SSR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSR', '0004_alter_girl_ssrs_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='ssrs_detail',
            field=models.JSONField(default=SSR.models.Girl.ssr_detail),
        ),
    ]
